title: 和歌山県串本町
description: 和歌山県串本町内でテイクアウトできるお店
data_url: https://docs.google.com/spreadsheets/d/1zyZQcaK3sREB59gv34aPAvk6NOktLe4P5gM42XmKmAc/export?format=csv&gid=0
repository: https://github.com/iemeshi/app/
form: https://docs.google.com/forms/d/1HZw3bCQ2Rt-0IYJyEfj2IlWS0OvgiGXklkKZ74Se6T0/edit?no_redirect
